version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: friendlorant

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      AUTH_DATABASE_DSN: "postgres://postgres:postgres@postgres:5432/friendlorant?sslmode=disable"
